"""
Report Exporter
Generate privacy-safe one-pager reports (PNG/PDF)
"""
import json
import logging
from typing import Dict, Any, Optional
from datetime import datetime
import io

logger = logging.getLogger(__name__)


def create_export_payload(
    coverage_percent: float,
    missing_skills: list[str],
    skills_by_category: Dict[str, list[str]],
    ai_recommendations: Optional[Dict[str, Any]],
    target_role_label: str,
    mode: str = "Role"
) -> Dict[str, Any]:
    """
    Create export payload with no PII.
    
    Args:
        coverage_percent: Match percentage
        missing_skills: Gap analysis
        skills_by_category: Categorized skills found
        ai_recommendations: AI insights (optional)
        target_role_label: Role name or "Custom JD"
        mode: "Role" or "Custom JD"
        
    Returns:
        Export payload dict
    """
    payload = {
        "version": "0.4.0",
        "timestamp_iso": datetime.utcnow().isoformat() + "Z",
        "mode": mode,
        "target_role_label": target_role_label,
        "coverage_percent": round(coverage_percent, 1),
        "missing_skills": missing_skills[:20],  # Limit to top 20
        "skills_by_category": skills_by_category,
        "total_skills": sum(len(skills) for skills in skills_by_category.values())
    }
    
    # Add AI insights if available
    if ai_recommendations:
        payload["ai"] = {
            "learning_path": ai_recommendations.get("learning_path", ""),
            "project_ideas": ai_recommendations.get("project_ideas", ""),
            "top_missing_skills": ai_recommendations.get("top_missing_skills", ""),
            "resume_tweaks": ai_recommendations.get("resume_tweaks", "")
        }
    
    return payload


def to_json(payload: Dict[str, Any]) -> str:
    """
    Convert payload to pretty JSON string.
    
    Args:
        payload: Export payload
        
    Returns:
        Formatted JSON string
    """
    return json.dumps(payload, indent=2, ensure_ascii=False)


def to_text_report(payload: Dict[str, Any]) -> str:
    """
    Generate a plain text report (fallback for systems without image libraries).
    
    Args:
        payload: Export payload
        
    Returns:
        Formatted text report
    """
    lines = []
    lines.append("=" * 60)
    lines.append("SKILLLENS RESUME ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append(f"Generated: {payload['timestamp_iso']}")
    lines.append(f"Target Role: {payload['target_role_label']}")
    lines.append(f"Mode: {payload['mode']}")
    lines.append("")
    
    lines.append(f"COVERAGE: {payload['coverage_percent']}%")
    lines.append(f"Total Skills Found: {payload['total_skills']}")
    lines.append("")
    
    lines.append("YOUR SKILLS BY CATEGORY:")
    lines.append("-" * 60)
    for category, skills in payload['skills_by_category'].items():
        if skills:
            lines.append(f"{category.upper()}: {', '.join(skills)}")
    lines.append("")
    
    if payload['missing_skills']:
        lines.append("MISSING SKILLS (Top Priority):")
        lines.append("-" * 60)
        for i, skill in enumerate(payload['missing_skills'][:10], 1):
            lines.append(f"{i}. {skill}")
        lines.append("")
    
    if 'ai' in payload:
        ai = payload['ai']
        lines.append("AI INSIGHTS:")
        lines.append("-" * 60)
        
        if ai.get('top_missing_skills'):
            lines.append("\nPriority Skills:")
            lines.append(ai['top_missing_skills'])
        
        if ai.get('learning_path'):
            lines.append("\nLearning Path:")
            lines.append(ai['learning_path'])
        
        if ai.get('project_ideas'):
            lines.append("\nProject Ideas:")
            lines.append(ai['project_ideas'])
        
        if ai.get('resume_tweaks'):
            lines.append("\nResume Tips:")
            lines.append(ai['resume_tweaks'])
        lines.append("")
    
    lines.append("=" * 60)
    lines.append("Generated by SkillLens v0.4.0 - Privacy-first resume analyzer")
    lines.append("=" * 60)
    
    return "\n".join(lines)


def generate_html_report(payload: Dict[str, Any]) -> str:
    """
    Generate HTML report suitable for PDF conversion or direct download.
    
    Args:
        payload: Export payload
        
    Returns:
        HTML string
    """
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SkillLens Report - {payload['target_role_label']}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
            color: #333;
        }}
        .header {{
            text-align: center;
            border-bottom: 3px solid #6366F1;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            color: #6366F1;
            margin: 0;
        }}
        .metadata {{
            background: #F3F4F6;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }}
        .coverage {{
            font-size: 48px;
            font-weight: bold;
            color: #6366F1;
            text-align: center;
            margin: 20px 0;
        }}
        .section {{
            margin-bottom: 30px;
        }}
        .section h2 {{
            color: #1F2937;
            border-left: 4px solid #6366F1;
            padding-left: 12px;
            margin-bottom: 15px;
        }}
        .skill-category {{
            margin-bottom: 15px;
        }}
        .skill-category h3 {{
            color: #4B5563;
            font-size: 14px;
            text-transform: uppercase;
            margin-bottom: 8px;
        }}
        .skill-tag {{
            display: inline-block;
            background: #DBEAFE;
            color: #1E40AF;
            padding: 4px 12px;
            border-radius: 16px;
            margin: 4px;
            font-size: 14px;
        }}
        .missing-skill {{
            display: inline-block;
            background: #FEF3C7;
            color: #92400E;
            padding: 4px 12px;
            border-radius: 16px;
            margin: 4px;
            font-size: 14px;
        }}
        .ai-insight {{
            background: #F0F9FF;
            padding: 15px;
            border-left: 4px solid #0EA5E9;
            margin-bottom: 15px;
            border-radius: 4px;
        }}
        .footer {{
            text-align: center;
            color: #6B7280;
            font-size: 12px;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #E5E7EB;
        }}
        @media print {{
            body {{ margin: 0; padding: 20px; }}
            .no-print {{ display: none; }}
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 SkillLens Analysis Report</h1>
        <p>Privacy-First Resume Skill Analyzer</p>
    </div>
    
    <div class="metadata">
        <strong>Target Role:</strong> {payload['target_role_label']}<br>
        <strong>Mode:</strong> {payload['mode']}<br>
        <strong>Generated:</strong> {payload['timestamp_iso']}<br>
        <strong>Total Skills Found:</strong> {payload['total_skills']}
    </div>
    
    <div class="coverage">
        {payload['coverage_percent']}% Match
    </div>
    
    <div class="section">
        <h2>Your Skills</h2>
"""
    
    # Add skills by category
    for category, skills in payload['skills_by_category'].items():
        if skills:
            html += f"""
        <div class="skill-category">
            <h3>{category}</h3>
            <div>
"""
            for skill in skills:
                html += f'                <span class="skill-tag">{skill}</span>\n'
            html += """
            </div>
        </div>
"""
    
    # Add missing skills
    if payload['missing_skills']:
        html += """
    </div>
    
    <div class="section">
        <h2>Missing Skills (Priority)</h2>
        <div>
"""
        for skill in payload['missing_skills'][:20]:
            html += f'            <span class="missing-skill">{skill}</span>\n'
        html += """
        </div>
    </div>
"""
    
    # Add AI insights if available
    if 'ai' in payload:
        ai = payload['ai']
        html += """
    <div class="section">
        <h2>AI Career Insights</h2>
"""
        
        if ai.get('top_missing_skills'):
            html += f"""
        <div class="ai-insight">
            <strong>Priority Skills:</strong><br>
            {ai['top_missing_skills']}
        </div>
"""
        
        if ai.get('learning_path'):
            html += f"""
        <div class="ai-insight">
            <strong>Learning Path:</strong><br>
            {ai['learning_path']}
        </div>
"""
        
        if ai.get('project_ideas'):
            html += f"""
        <div class="ai-insight">
            <strong>Project Ideas:</strong><br>
            {ai['project_ideas']}
        </div>
"""
        
        if ai.get('resume_tweaks'):
            html += f"""
        <div class="ai-insight">
            <strong>Resume Tips:</strong><br>
            {ai['resume_tweaks']}
        </div>
"""
        
        html += """
    </div>
"""
    
    html += """
    <div class="footer">
        Generated by SkillLens v0.4.0<br>
        Privacy-first • No resume text stored or transmitted<br>
        © 2025 SkillLens
    </div>
</body>
</html>
"""
    
    return html


# Graceful fallback without heavy dependencies
logger.info("Export module loaded. HTML and JSON export available. PDF/PNG require optional dependencies.")
